AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'app/channels/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'config.ru'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# Layout/EndOfLine:
#   Exclude:
#     - 'app/models/**/*'
    # - 'app/controllers/application_controller.rb'